### ISSUE TITLE
Can't load addon in Godot 4

### ISSUE THREAD

**Issue by goudcode** [cybereality/godot-space-mouse#2]
I'm not sure if this add-on has support for Godot 4, but when I try to load it into my project I get the message: 
```
Unable to load addon script from path: 'res://addons/spacemouse/SpaceMouse.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/spacemouse/plugin.cfg' to prevent further errors.
```

The Output console gives the following information:

```
  res://addons/spacemouse/SpaceMouse.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:870 - Method/function failed. Returning: ERR_PARSE_ERROR
  Transient parent has another exclusive child.
  core/config/project_settings.cpp:319 - Property not found: editor_plugins/enabled
  res://addons/spacemouse/SpaceMouse.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:870 - Method/function failed. Returning: ERR_PARSE_ERROR
  Transient parent has another exclusive child.
```

I am using the Alpha 11 build (Windows), if there is any help needed to get this going on Godot 4 I would gladly help with this.

**Comment by cybereality** [comment]
Sorry, I should have noted that this is for Godot 3.x. I've tested on Godot 3.4.4, it may work on other versions. But I haven't made a Godot 4.0 version. Thanks for bringing this to my attention, but I am going to wait until the API in finalized or when a stable version comes out to update the plugin. Because the whole system for plugins is new, and also the GDScript syntax has changed, so it's not worth it to update until the API is finalized. But I am planning to do this at some point.

**Comment by goudcode** [comment]
Fair enough, thanks for developing this add-on.

**Comment by cybereality** [comment]
Thanks for the interest, through. I would make a beta version, but I'm on my final classes for computer science and I don't have a lot of extra time for non-essentials. However, maybe in a month or two I can start some research and see if it is not that complex to get Godot 4.0 support. It's just not a huge priority at the moment, but I'll get to it when I have time.
